AWSTemplateFormatVersion: 2010-09-09
Description: Default Module Version and Registry

Parameters:

  pModuleName:
    Type: String
    Description: Module name that you want to register
    Default: 'My::CloudWatch::SampleAlarm::MODULE'

  pModulePackage:
    Type: String
    Description: s3 bucket for where your module is stored
    Default: 's3://cf-modules-sandbox/CW-Module-Package'

Resources:
  rCWModuleVersion1:
    Type: AWS::CloudFormation::ModuleVersion
    Properties:
      ModuleName: !Ref pModuleName
      ModulePackage: !Ref pModulePackage

  rModuleDefaultVersion:
    Type: AWS::CloudFormation::ModuleDefaultVersion
    Properties:
      Arn: !Ref rCWModuleVersion1